"""changed project model

Revision ID: 22ef45cb8382
Revises: 
Create Date: 2025-08-10 00:03:30.315842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ef45cb8382'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный ID'),
    sa.Column('name', sa.String(), nullable=True, comment='Наименование организации'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный ID'),
    sa.Column('name', sa.String(), nullable=True, comment='Наименование'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Организация заказчик'
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный id'),
    sa.Column('text', sa.String(), nullable=True, comment='Текст комментария'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text'),
    comment='Комментарии к проекту'
    )
    op.create_table('contract_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный идентификатор'),
    sa.Column('code', sa.Integer(), nullable=False, comment='Числовой код статуса'),
    sa.Column('explanations', sa.String(length=255), nullable=False, comment='Текстовое описание статуса'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('explanations'),
    comment='Справочник статусов договоров'
    )
    op.create_table('expense',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный ID'),
    sa.Column('type', sa.String(), nullable=False, comment='Тип расходов'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type'),
    comment='Расходы'
    )
    op.create_table('field',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный id'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Наименование сферы детельности'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Сфера деятельности'
    )
    op.create_table('investor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный id'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Инвестор'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Справочник инвесторов'
    )
    op.create_table('tk',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный ID'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Транспортная компания'
    )
    op.create_table('transaction_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный ID'),
    sa.Column('name', sa.String(), nullable=False, comment='Тип сделки'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Тип сделки'
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.drop_table('transaction_type')
    op.drop_table('tk')
    op.drop_table('investor')
    op.drop_table('field')
    op.drop_table('expense')
    op.drop_table('contract_status')
    op.drop_table('comments')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('agents')
    # ### end Alembic commands ###
